### ISSUE TITLE
Got Fatal Error while building a project

### ISSUE THREAD

**Issue by vborodav** [cpisciotta/xcbeautify#1]
`Fatal error: ["build/CocoaLumberjack.framework"]: file /Users/admin/dev/xcbeautify/Sources/XcbeautifyLib/String+Beautify.swift, line 164`

I can provide you with more info if required

**Comment by thii** [comment]
@vborodav Thanks for reporting! This has been fixed in 0.3.5. Please run `brew update && brew upgrade xcbeautify` to update it.

**Comment by vborodav** [comment]
@thii  thanks for the tool )
