### ISSUE TITLE
Command line option to output issue only

### ISSUE THREAD

**Issue by greensky01** [cpisciotta/xcbeautify#13]
Is it possible to add a command line options to display warnings or errors only? Because for a huge project, most of output "[XXX] Compiling YYY.cpp" are of less importance and they would hide real issues.

**Comment by thii** [comment]
@greensky01 Thanks for opening this issue. I agree that this is a nice feature to have. Although there’s a workaround for this by using xcodebuild’s `-quiet` flag to tell it to only print warnings and errors output, and piping that output to xcbeautify, we wouldn’t be able to keep the original raw log if we need to.

Do you have to tackle on this?

**Comment by thii** [comment]
@greensky01 I did an initial implementation of the `quiet` feature at https://github.com/thii/xcbeautify/tree/quiet-flag. Could you try to see if it works for you? (You would need to build it from source)

**Comment by greensky01** [comment]
WOW!! Thank you @thii ! 
I'll give it a try tomorrow, and come back to you then. :)

**Comment by greensky01** [comment]
Hi @thii , I've tried the new quite feature, and it works well for me. 

However, I also feel that for some certain warnings, if xcbeautify does not display what it's doing, it could be difficult to know where this warning comes from. Personally I'd prefer the quiet mode display info in the following way:

[Target Name] Compiling XXX.m
Warning message content.

Another question, would you allow others to submit code? If it's okay for you, do I need to follow any contribution rules?

Thanks.

**Comment by thii** [comment]
> However, I also feel that for some certain warnings, if xcbeautify does not display what it's doing, it could be difficult to know where this warning comes from. Personally I'd prefer the quiet mode display info in the following way:
>
> [Target Name] Compiling XXX.m
> Warning message content.

That makes sense. I'll see if we could do that.

> Another question, would you allow others to submit code? If it's okay for you, do I need to follow any contribution rules?

Of course. Just submit a pull request.
