### ISSUE TITLE
Submit xcbeautify to Homebrew

### ISSUE THREAD

**Issue by thii** [cpisciotta/xcbeautify#2]
Someone other than the project maintainer has to do this.

**Comment by yonaskolb** [comment]
Hi, great project!
That is an old rule I believe. You can submit it yourself 👍

**Comment by thii** [comment]
Thanks. I would prefer someone other than me submitting it anyway.

**Comment by revolter** [comment]
Why?

**Comment by onmyway133** [comment]
@thii Hi, I'm gonna use yours in replacement for xcpretty in my new Swift build tool, it 's gonna be a great project. How can I contact you

**Comment by thii** [comment]
@onmyway133 You can find my email from one of the commits.

**Comment by onmyway133** [comment]
@thii Can you change the Package.swift to support library, besides executable? I want to use XcbeautifyLib directly, otherwise I have to embed that code

**Comment by thii** [comment]
@onmyway133 Do you mind submitting a PR to add it? Otherwise I'll do it later when I can make some time for this.

**Comment by onmyway133** [comment]
@thii PR submitted https://github.com/thii/xcbeautify/pull/8

**Comment by xavierjurado** [comment]
Still looking for someone to submit the formula to Homebrew @thii ?

**Comment by thii** [comment]
@xavierjurado It was rejected a while ago due to not popular enough. I guess I'll wait a bit more.

**Comment by mRs-** [comment]
I think it' safe now to submit it to homebrew. You only need 40 Stars to submit it at Homebrew 😀

**Comment by thii** [comment]
@mRs- Would you mind to try? :)

**Comment by mRs-** [comment]
Yeah can do that. Do you have a tutorial for me? This is the first time doing this 😄

**Comment by thii** [comment]
Please take a look at my previous submission https://github.com/Homebrew/homebrew-core/pull/41003.

**Comment by ealeksandrov** [comment]
`xcbeautify` successfully added to homebrew-core: [xcbeautify.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/xcbeautify.rb)

**Comment by thii** [comment]
@ealeksandrov Thanks a lot!
