### ISSUE TITLE
Linux, Swift 5.1.2, `swift test` doesn't show test cases

### ISSUE THREAD

**Issue by Cyberbeni** [cpisciotta/xcbeautify#20]
output with xcbeautify: https://github.com/Cyberbeni/TypedNotificationCenter/runs/314794146
output without xcbeautify: https://github.com/Cyberbeni/TypedNotificationCenter/runs/303631505

**Comment by thii** [comment]
Use this:
```
swift test 2>&1 > /dev/null | xcbeautify
```

**Comment by Cyberbeni** [comment]
That just results in no output.

The problem is that `swift test` outputs stuff like this:
```
Test Case 'ApiTests.testNotificationWithDifferentObject' passed (0.0 seconds)
```
Which I'm pretty sure doesn't match `case testCasePassed = #"\s*Test Case\s'-\[(.*)\s(.*)\]'\spassed\s\((\d*\.\d{3})\sseconds\)."#`

**Comment by thii** [comment]
I’ll take a look later when I’m near a computer, but if you could submit a PR to fix it it’d be awesome.
