### ISSUE TITLE
[New Output] Support "Testing started" Output

### ISSUE THREAD

**Issue by cpisciotta** [cpisciotta/xcbeautify#206]
### What's the uncaptured output?

```
Testing started
```

### Suggested Regex

```regex
^Testing started$
```

**Comment by ikelax** [comment]
Where does this output come from?

**Comment by ikelax** [comment]
@cpisciotta Do you have a log containing this output?

**Comment by cpisciotta** [comment]
Hey @ikelax. You can see this output with the following command.

```sh
xcodebuild test -scheme xcbeautify-Package -destination 'platform=macOS,arch=arm64'
```

The entire line is `Testing started`.
