### ISSUE TITLE
Add support for private performance metrics

### ISSUE THREAD

**Issue by Cyberbeni** [cpisciotta/xcbeautify#25]
Xcode supports more stuff to performance test than just "wall clock time", it would be cool to also see those in the formatted output

https://indiestack.com/2018/02/xcodes-secret-performance-tests/

**Comment by thii** [comment]
Did you not see the formatted output for performance tests? If not, it could be a bug.

**Comment by Cyberbeni** [comment]
There are different measurements, like Persistent VM/Heap allocations, the formatted output only contains time based measurements.

**Comment by thii** [comment]
I’d love to see a PR :)
