### ISSUE TITLE
Homebrew surfacing a v2.0.0 that isn't on the releases page?

### ISSUE THREAD

**Issue by liamjones** [cpisciotta/xcbeautify#267]
Not sure if this is something to report here or homebrew - homebrew just started prompting me to update from 1.6.0 to 2.0.0 but I don't see it listed on the release pages? Looks like 2.0.0 is still a beta with only pre-release versions (which I don't think Homebrew should pick up?)

**Comment by cpisciotta** [comment]
Hi @liamjones. Thanks for filing the issue, and I'm sorry for the inconvenience. I recently attempted to release 2.0.0, but I had to revert it; however, it seems I only deleted the release without deleting the tag too. I think I've fixed the issue, and you can find 2.0.0 [here](https://github.com/cpisciotta/xcbeautify/releases/tag/2.0.0). Please try to re-install 2.0.0, and let me know if you encounter any additional issues.

**Comment by liamjones** [comment]
@cpisciotta thanks, that sorted it. Homebrew has also picked up 2.0.1 now. 👍
