### ISSUE TITLE
Fail to output properly on Xcode 11.3

### ISSUE THREAD

**Issue by greensky01** [cpisciotta/xcbeautify#27]
Hi @thii,

We encounter this issue again since you fixed the same issue (#23 ) for Xcode 11.2... Unstable format of xcodebuild output is a real headache for xcbeautify.

Could you take a look?

**Comment by thii** [comment]
Could you give me an example input? Just one line is enough.

**Comment by greensky01** [comment]
Hi @thii, is the following snippet enough?

CompileC /Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/Objects-normal/x86_64/main.o /Users/user_name/Desktop/FirstStep/FirstStep/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirstStep' from project 'FirstStep')
    cd /Users/user_name/Desktop/FirstStep
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-macos10.15 -fmessage-length=229 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/6l/f6ytm9bd4yd795xs15jlblr80000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/FirstStep-generated-files.hmap -I/Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/FirstStep-own-target-headers.hmap -I/Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/FirstStep-all-target-headers.hmap -iquote /Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/FirstStep-project-headers.hmap -I/Users/user_name/Desktop/FirstStep/build/Release/include -I/Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/DerivedSources-normal/x86_64 -I/Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/DerivedSources/x86_64 -I/Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/DerivedSources -F/Users/user_name/Desktop/FirstStep/build/Release -MMD -MT dependencies -MF /Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/Objects-normal/x86_64/main.d --serialize-diagnostics /Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/Objects-normal/x86_64/main.dia -c /Users/user_name/Desktop/FirstStep/FirstStep/main.m -o /Users/user_name/Desktop/FirstStep/build/FirstStep.build/Release/FirstStep.build/Objects-normal/x86_64/main.o

**Comment by thii** [comment]
Here is what I got:
```
[FirstStep] Compiling main.m
[/Users/user_name/Desktop/FirstStep/FirstStep/main.m] Compiling /Users/user_name/Desktop/FirstStep/FirstStep/main.m
```

Looked like it also formatted the actually compiling command, so you get an additional output to your console. I really don't have bandwidth to look at this at the moment so if you can submit a PR, I would be happy to take it.

**Comment by greensky01** [comment]
Hi @thii ,

I'd love to help with this, but please expect it may take some time.
