### ISSUE TITLE
xcbeautify Podspec points to wrong repo

### ISSUE THREAD

**Issue by pehagg** [cpisciotta/xcbeautify#299]
The [Podspec for 0.17.0](https://github.com/CocoaPods/Specs/blob/master/Specs/5/3/d/xcbeautify/0.17.0/xcbeautify.podspec.json)  points to `tuist/xcbeautify` repo, which doesn't have the releases available (anymore?) 

Any chance this could be fixed? It's causing build problems for us when we have xcbeautify as dependency in our Podfile. The binary itself is used in our Fastlane script. Even though dated, 0.17.0 is the latest version available in Cocoapods.

**Comment by cpisciotta** [comment]
Hi @pehagg! Thanks for your patience, and sorry for the inconvenience. 

Please see a similar report and workaround [here](https://github.com/cpisciotta/xcbeautify/discussions/298). You should be able to explicitly specify xcbeautify's URL (https://github.com/cpisciotta/xcbeautify) as a workaround to this issue. Please let me know if you still encounter issues.

---

Tuist once maintained this repository, so their fork is causing some URL redirect issues. I've requested that they temporarily delete it, until I update the Cocoapods podspec.

**Comment by pehagg** [comment]
Thanks for the workaround, I totally forgot that you can define the git repo as the source. Closing issue.
