### ISSUE TITLE
Logs Delayed When Using GitHub Actions with GitHub Hosted Runners

### ISSUE THREAD

**Issue by AllDmeat** [cpisciotta/xcbeautify#315]
When running tests locally, logs are output immediately and in real-time. However, when running the same tests in our CI pipeline using GitHub Actions, there is a noticeable delay. Logs are often dumped all at once after the tests have finished, rather than streaming incrementally.

Environment:
- xcbeautify: 2.11.0
- runners: GitHub Hosted, macos-latest

Step:
```
set -o pipefail

xcodebuild test-without-building \
-derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
-destination 'platform=iOS Simulator,id=${{ steps.create_simulator.outputs.uuid }}' \
-xctestrun "$xctestrun" \
-resultBundlePath "$xcresults_name" \
| xcbeautify --renderer github-actions
```

Is there a specific flag or configuration that needs to be adjusted for xcbeautify to work correctly with GitHub Actions and GitHub Hosted Runners? Any guidance or suggestions to resolve this issue would be greatly appreciated.

**Comment by tonyarnold** [comment]
Hi @AllDmeat — have you tried prepending `NSUnbufferedIO=YES` to your `xcodebuild` execution? There's a [more information on this environment variable available on NSHipster](https://nshipster.com/launch-arguments-and-environment-variables/#io-buffering).

**Comment by AllDmeat** [comment]
@tonyarnold worked like a charm, thanx a lot 👍

```yml
- name: Run Tests
  id: tests
  env:
    NSUnbufferedIO: YES
  run: |
    xcodebuild test-without-building ...
```
