### ISSUE TITLE
Supression of warnings

### ISSUE THREAD

**Issue by jgonet** [cpisciotta/xcbeautify#36]
Hi, thanks for the great project.

One thing I'm missing from it is the warnings suppression - Travis cancel jobs after 4MB of logs and building React Native projects for IOS often generates many warnings for the third party libraries.

Using some flag like `--errors-only` would be very helpful in that case

**Comment by thii** [comment]
Have you tried using the `--quiet` flag?

**Comment by jgonet** [comment]
It filters only warnings and errors, doesn't it? I want to get rid of warnings entirely and keep only errors

**Comment by thii** [comment]
Use xcodebuild -quiet.

**Comment by jgonet** [comment]
From xcodebuild docs:
```
     -quiet
           Do not print any output except for warnings and errors.
```

it does print warnings.

**Comment by thii** [comment]
Oops, I thought it suppresses warnings.

Quick thoughts — there are two ways you can achieve that:
- Suppress the warnings yourself. If you use CocoaPods, you can do it via a post-install script. 
- Contribute to this tool by adding a new flag (probably named -quieter). I’ll be more than happy to review it.

**Comment by jgonet** [comment]
I actually ended up using egrep to filter them out.

Thanks for the suggestion, I might try to do it
