### ISSUE TITLE
Parallel tests are not matched

### ISSUE THREAD

**Issue by mpaddle** [cpisciotta/xcbeautify#4]
I've been trying `xcbeautify` out with a parallel test suite, but the tests are not being matched. Below is some of the unparsed output from `xcodebuild`. Might be worth noting that the test suite is written in Objective-C, but I doubt it makes a difference.

```
Testing started on 'My Mac'
Test suite 'MyControllerTests' started on 'xctest (49438)'
Test suite 'MyTests' started on 'xctest (49440)'
Test case '-[MyControllerTests testErrorReported]' passed on 'xctest (49438)' (0.301 seconds)
Test case '-[MyControllerTests testTheThingIsChanged]' passed on 'xctest (49438)' (0.005 seconds)
Test case '-[MyControllerTests testAllTheThings]' passed on 'xctest (49438)' (0.001 seconds)
Test suite 'MyServiceTests' started on 'xctest (49438)'
Test case '-[MyServiceTests testServiceActuallyWorks]' passed on 'xctest (49438)' (0.004 seconds)
```

The regex pattern matching the passed tests doesn't expect the `on 'xctest (49438)'` part and there is no arbitrary character at the end of the line. Does it make sense to simply ignore the process part and make the arbitrary character optional? Personally I don't care about the process ID of the test, but happy to discuss that.

I'm also happy to put in a PR for this. Seems fair because I'd like to see this fixed 🙂

**Comment by thii** [comment]
Hi @mpaddle 👋 ! Thanks for trying **xcbeautity** and thanks for reporting this. I wasn't aware of the process number in `xcodebuild` output. I'm guessing this is probably for AppKit apps only? I'll take a look next week but if you could put in a PR for this it would be greatly appreciated!

**Comment by mpaddle** [comment]
Hi @thii 👋 Yes, this is from an AppKit product. I've submitted a PR to close this issue, but there are a few other cases missing, I think. When I have time I'll figure out the missing cases in detail and raise a separate issue.
