### ISSUE TITLE
[SOLVED] `swift test | xcbeautify` on macOS doesn't work

### ISSUE THREAD

**Issue by Cyberbeni** [cpisciotta/xcbeautify#48]
The swift CLI on macOS prints to the error output, so `swift test 2>&1 | xcbeautify` will work correctly.

**Comment by Cyberbeni** [comment]
Wait, this is not the cause of the issue... 🤔

**Comment by Cyberbeni** [comment]
OMG. The swift CLI on macOS prints to the error output... So `swift test 2>&1 | xcbeautify` will work correctly.

@thii do we want to keep this issue with a different name with a "has solution" tag or just close it?

**Comment by thii** [comment]
FYI this repo's CI does exactly that.

You can rename this issue.
