### ISSUE TITLE
Support NO_COLOR env var

### ISSUE THREAD

**Issue by Cyberbeni** [cpisciotta/xcbeautify#49]
https://no-color.org/

"All command-line software which outputs text with ANSI color added should check for the presence of a NO_COLOR environment variable that, when present (regardless of its value), prevents the addition of ANSI color."

**Comment by pieterclaerhout** [comment]
Seems to be integrated already in https://github.com/thii/xcbeautify/pull/46

**Comment by Cyberbeni** [comment]
That's just an input flag. This is an environment variable often used by CI systems that don't support colored output, so it would save the time for people wondering what is the html encoded like text they are seeing in their CI logs.

**Comment by pieterclaerhout** [comment]
Submitted a PR which implements the environment variable.
