### ISSUE TITLE
Lib can't be used from Swift code (because of `readLine`)

### ISSUE THREAD

**Issue by MortenGregersen** [cpisciotta/xcbeautify#53]
When I use the XcbeautifyLib from Swift code it "stops" if [it encounters a compile warning](https://github.com/thii/xcbeautify/blob/master/Sources/XcbeautifyLib/Parser.swift#L161). This happens because of the call to [`readLine()`](https://github.com/thii/xcbeautify/blob/master/Sources/XcbeautifyLib/String%2BBeautify.swift#L422) in `formatCompileWarning`.

Could we only call `readLine` when the lib is used from the command line tool? Maybe by setting an environment variable in `main.swift`?

**Comment by swiftyfinch** [comment]
I have the same issue. I wonder if this repo is maintained? Probably, I can make a pull request.

**Comment by thii** [comment]
Yes, it is. Please make a pull request :)
