### ISSUE TITLE
how can we use xcbeautify with fastlane?

### ISSUE THREAD

**Issue by ykhandelwal913** [cpisciotta/xcbeautify#54]
Fastlane ships with xcpretty but when running tests in parallel, it doesnot create correct output. Hence we want to use xcbeautify with fastlane.
Is there any way we can use that with action run_tests? https://docs.fastlane.tools/actions/run_tests/

**Comment by thii** [comment]
Can fastlane print unformatted output? If it can, then you can then pipe that output to xcbeautify.

**Comment by pepicrft** [comment]
Love this idea, I think we can extend the `run_tests` action to support choosing the formatter. Thoughts @joshdholtz ?

**Comment by joshdholtz** [comment]
I have an open PR that will allow xcbeautify support everywhere in fastlane while also removing any dependencies on XCPretty 🙂 I'm hoping to get it released next week 💪

**Comment by joshdholtz** [comment]
Here you go! `2.201.0.rc1` has support to use `xcbeautify` 🙂

https://github.com/fastlane/fastlane/pull/19629

**Comment by pepicrft** [comment]
In that case, I'll close this issue.

**Comment by blwinters** [comment]
For using it on CI, because xcbeautify has to be installed, I added it as a Cocoapod and then specified the install location, so in my Fastfile I have
```
build_app(
    ...
    xcodebuild_formatter: "Pods/xcbeautify/xcbeautify --quieter"
)
```
