### ISSUE TITLE
Much slower than xcpretty

### ISSUE THREAD

**Issue by brennantaylor** [cpisciotta/xcbeautify#6]
Hi there. Not knocking the tool or anything I really like it and want to make it better. I was trying it out on our build's output and noticed it was very very slow. Was going to open an issue now and dig into profiling it. I imagine its something simple like regex's being created more often than necessary or something similar. Below is a comparison of timing on our unittest output between `xcpretty` and `xcbeautify`.

```
 ~/dev > du -hs xcodebuild.log
3.0M    xcodebuild.log
 ~/dev > cat xcpretty.sh xcbeautify.sh
#!/bin/bash
cat xcodebuild.log | xcpretty > /dev/null
#!/bin/bash
cat xcodebuild.log | xcbeautify > /dev/null
 ~/dev > time ./xcpretty.sh
        1.34 real         1.18 user         0.14 sys
 ~/dev > time ./xcbeautify.sh
       52.34 real        52.23 user         0.06 sys
```

**Comment by thii** [comment]
Hi there,

Thanks for opening this issue. I am already aware of this but haven’t had time to take a look. It’s definitely the first thing to look at when I can manage to work on this again.

**Comment by brennantaylor** [comment]
#7 fixed this. Thanks @thii
