### ISSUE TITLE
Support for generation of compilation database

### ISSUE THREAD

**Issue by acecilia** [cpisciotta/xcbeautify#60]
Hi 👋 

Would be nice to support the generation of compilation databases. Xcpretty seems to support this already: https://github.com/xcpretty/xcpretty#reporters

Thanks!

**Comment by pepicrft** [comment]
@acecilia would you like to generate an HTML report from your compilation?

**Comment by acecilia** [comment]
Mmm what do you mean? Sorry, I dont understand the question

At the time of writing, my goal was to generate a compilation database to pass to swiftlint. After looking into it, I end up writing a script to manually generate it

**Comment by lk23lekkladf2** [comment]
@acecilia would you mind sharing the scripts that you ended using to create the compilation database? thanks!

**Comment by acecilia** [comment]
See some examples here: https://github.com/acecilia/swift-compilation-database

**Comment by KarthikJay** [comment]
xcpretty supports generation of compile_commands.json files using the following flag:
-r json-compilation-database

Currently, xcbeautify doesn't support this reporter:
The value 'json-compilation-database' is invalid for '--report <report>'

**Comment by adenisonafifi** [comment]
The compilation database can be used by clangd for code completion when working outside of XCode on a Mac C++ project. This is a great feature from xcpretty but now the xcpretty project is unsupported.

**Comment by moshe-foreflight** [comment]
+1 for compilation database.

**Comment by jaysoffian** [comment]
Parsing the output of xcodebuild to generate a compilation database is fraught with peril. Use `-gen-cdb-fragment-path` instead. See https://gist.github.com/T1T4N/f4d63a44476eb5c7046cc561cb8c7f77 for guidance.

**Comment by jmonroe** [comment]
+1 on this.  
The compilation database is required for SonarScanner to scan projects correctly.
