### ISSUE TITLE
Would you accept a PR adding junit test report generation?

### ISSUE THREAD

**Issue by acecilia** [cpisciotta/xcbeautify#61]
Hi 👋 

Would you accept a PR adding junit test report generation?

Context:
* When using bazel, trainer cant be used to read the xcode plists
* When using bazel, XCTestHTMLReport cant be used to read the xcresult [under some scenarios](https://github.com/google/xctestrunner/issues/26)

So the only thing available seems to be the test log. If the output of xcbeautify is reliable enough, generating a junit report from it may be a good alternative

**Comment by thii** [comment]
Hi 👋
A PR is very welcomed!
