### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by thii** [cpisciotta/xcbeautify#62]
This was a weekend hack a few years ago to work around the parallel testing feature in Xcode 9 not being supported by xcpretty. Even though I don't use this anymore, it seems like there are still people that depends on it. I don't have time in maintaining this project for much longer, but also don't want to break anyone's builds. If you're interested in taking it over, please contact me.

**Comment by orj** [comment]
Wish I had time to volunteer to be maintainer. Really appreciate you creating this tool @thii

**Comment by mikehardy** [comment]
Oh no! Wish I had more (any) Swift skills. This project hits the sweet spot between `-quiet` and unfiltered.
Looks like the release process is totally automated and everything? (release.yml workflow, your tokens set up etc)
CI looks good.

I'm not sure I can help *that* much but it also doesn't seem that hard to keep the project going. I could at least merge PRs and kick out releases.

I won't be able to generate PRs until I learn Swift (it's bound to happen - I'm a react-native dev mostly and we're Objective-C still but Swift is starting to happen in the ecosystem...)

**Comment by byaruhaf** [comment]
@thii how can I contact you, I'm interested in taking it over.

**Comment by joshdholtz** [comment]
Really appreciate all you've done with this! ❤️

I can't take on the actual work but I can volunteer a spot for the repo in https://github.com/fastlane-community if it needs a home 🙃 Would still need some people to maintain it though!

**Comment by pepicrft** [comment]
This is very sad. Thanks a lot for making this project happen @thii. We use it extensively in tuist.io and we couldn't be happier about it. Would you be open to talk about the possibility of the Tuist organization taking on the maintenance role? The community is very active maintaining Tuist and XcodeProj, and there's bandwidth to support this so-needed piece of software

**Comment by thii** [comment]
Thanks everyone for all the offers, I really appreciate it. `xcbeautify` has joined the Tuist orgnization, so I'm closing this issue now.
