### ISSUE TITLE
xcbeautify hangs virtual machine on bitrise.io

### ISSUE THREAD

**Issue by pappalar** [cpisciotta/xcbeautify#68]
Hello!

I am sorry I can't provide many more debug details.
We are using `bitrise` with `fastlane` and `xcbeautify` to run our iOS builds.

all of our builds had extreme High CPU usage, and UI tests were getting completely stuck.

We checked the Bitrise VMs with a VNC and by checking the activity monitor we realized the cause of the freeze was the 
`xcbeautify` consuming all resources.

This is not causing a hang on our local machine, it's more tied to a VM environment.

Do you have any performance issue report regarding similar issues?
or any way we can enable some performance logs/monitoring for improving this report?
thanks

**Comment by pappalar** [comment]
note: removing `xcbeautify` solves the problem in our builds since the CPU usage does not spike

**Comment by itskoBits** [comment]
We are experiencing the same issue. Calling fastlane's `scan` action passing it `build_for_testing: true` causes compile time to skyrocket. Compiling a single file takes 2-3 seconds.

**Comment by nicolasrostan** [comment]
+1 to build time increasing when using scan and build_for_testing: true, we saw a 3x increase in build time, using jenkins with metal agents.
