### ISSUE TITLE
Can this support macOS 10.10+ ?

### ISSUE THREAD

**Issue by onmyway133** [cpisciotta/xcbeautify#9]
I see in Package.swift https://github.com/thii/xcbeautify/blob/master/Package.swift#L6 we specify macOS 10.14+? Can you lower the deployment target?

**Comment by thii** [comment]
Please use version 0.3.8. The latest version now uses Swift 5 (Xcode 10.2) that requires Mojave 10.14.3+ to build.

**Comment by thii** [comment]
Linking standard library statically has been removed in Swift 5 compiler, so even if I lower the deployment target, the program would still crash at runtime.

**Comment by onmyway133** [comment]
@thii thanks, then I need to go with 10.14 for now
