### ISSUE TITLE
A more detailed 'Usage guide'?

### ISSUE THREAD

**Issue by venkat2789** [cpisciotta/xcbeautify#92]
Where can i find more information on the usage of xcbeautify?

For e.g. `xcodebuild [flags] | xcbeautify`
- what are the different flags that can be used here?

How to generate a JUnit report from xcbeautify?

**Comment by dogo** [comment]
`xcbeautify --report junit`

**Comment by venkat2789** [comment]
@dogo thanks! I am eager to know what other capabilities are provided by xcbeautify and the different flags that can be used. That's why was looking for documentation.

**Comment by danieleformichelli** [comment]
@venkat2789 I guess `xcbeautify --help` shouldould provide all the information.

Regarding your specific questions `xcodebuild [flags] | xcbeautify`, those are flags of xcodebuild, so they shouldn't be documented by xcbeatufy, and also in that case `xcodebuild --help` could help

**Comment by venkat2789** [comment]
Thanks for clarifying, I was assuming the flags were from xcbeautify. And I can learn the xcbeautify features with --help once I install it.
