### ISSUE TITLE
Add an option which prints warning and error instead of the unicode character

### ISSUE THREAD

**Issue by hriekehof** [cpisciotta/xcbeautify#94]
Hi there. Thanks for this handy tool :)

I want to create a problem matcher for vscode in a custom task where i pipe the build output from `xcodebuild` through `xcbeautify`. In order to distinguish between and error and a warning i need to match the words as a string with a regex. VSCode can then present the errors and warnings in the problems tab and i can jump to them.
At the moment this is not working quite well since warning and error are printed by xcbeautify as `\u{9888}` and `\u{26A0}`. It would be nice if there were an option i can pass in and then `warning` and `error` is printed instead of the special unicode character.

**Comment by thii** [comment]
There's already an option called `--disable-colored-output`. You can also disable colored output by setting `NO_COLOR=1` in your environment variables.

**Comment by hriekehof** [comment]
Yes this would work. But i like the colored output since its much easier too read :) i'd like to have both. Colored without special unicode characters
