### ISSUE TITLE
publish release 0.16.0 to cocoapods

### ISSUE THREAD

**Issue by jjcoffman** [cpisciotta/xcbeautify#95]
Looks like JUnit support for parallel testing was added in 0.16.0, but it was not published to cocoapods. The latest version available there is 0.15.0, any chance it could be published?

Thanks!

**Comment by thii** [comment]
Looks like the CI release pipeline failed for that version. I've just published it now.

**Comment by thii** [comment]
Just released 0.17.0 as well.
