### ISSUE TITLE
Set up a new `COCOAPODS_TRUNK_TOKEN` secret

### ISSUE THREAD

**Issue by thii** [cpisciotta/xcbeautify#97]
The current one seems expired, and I don't have access to setting secrets in this repo.

https://github.com/tuist/xcbeautify/actions/runs/4213952579/jobs/7314070522

cc @tuist/core

**Comment by luispadron** [comment]
Hey @thii! Can take a look at this on Monday

**Comment by luispadron** [comment]
Ah wait I dont seem to either, looks like we have the same role 😄 

@pepicrft @fortmarek 🙏🏼

**Comment by cpisciotta** [comment]
Closing, since a recent PR (https://github.com/tuist/xcbeautify/pull/135) removed CocoaPods support.
